apiVersion: v1
kind: Service
metadata: 
 name: my-nodeport-service
spec:
 type: NodePort
 ports: 
 - name: http
   port: 3000
   targetPort: 3000
   nodePort: 30100
   protocol: TCP
 selector:
  app: lab2